name: CI

on: push

jobs:
  lint-all-files:
    strategy:
      matrix:
        elisp-check:
          - load-file
          - byte-compile
          - checkdoc
          - melpa
          - package-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: purcell/setup-emacs@v7.0
        with:
          version: 30.2
      - name: run linter on all files
        uses: leotaku/elisp-check@v1.3
        with:
          check: ${{ matrix.elisp-check }}
          file: "org-roam-readwise.el"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: purcell/setup-emacs@v7.0
        with:
          version: 30.2
      - name: run ERT tests
        run: emacs --batch -l org-roam-readwise-test.el -f ert-run-tests-batch-and-exit
